accounts/urls.py
from django.conf.urls import include, url
from accounts import views as accounts_views
from django.contrib.auth.views import (
        login, logout, password_reset,password_reset_done,
        password_reset_confirm, password_reset_complete
    )
urlpatterns = [
    url(r'^$', include('habits.urls')),
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^login/reset_password/$', password_reset, {'template_name': 'accounts/display_password_reset.html'}, name='password_reset'),
    url(r'^login/reset_password/done/$', password_reset_done, {'template_name': 'accounts/display_password_reset_done.html'}, name='password_reset_done'),
    url(r'^login/reset_password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm, {'template_name': 'accounts/display_password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^login/reset_password/complete/$', password_reset_complete, {'template_name': 'accounts/display_password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^registration/$', accounts_views.register, name='registration'),
    url(r'^registration/account_activation_sent/$', accounts_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', accounts_views.activate, name='activate'),
    url(r'^profile/$',accounts_views.view_profile, name='view_profile'),
    url(r'^profile/upload/$', accounts_views.upload_profile_image, name='upload_profile_image'),
    url(r'^profile/edit/$', accounts_views.edit_profile, name='edit_profile'),
    url(r'^profile/disable_account/confirm/$', accounts_views.disable_account_confirm, name='disable_account_confirm'),

    # url(r'^profile/edit/change_password/$', accounts_views.change_password, name='change_password'),

]

habits/urls.py
from django.conf.urls import include, url
from habits import views as habits_views

urlpatterns = [
    #url(r'^$', habits_views.display_habits, name='display_habits'),
    url(r'^$', habits_views.HabitListView.as_view(), name='display_habits'),

    url(r'^saveOrder/$', habits_views.HabitListView.as_view(), name='save_order'),

    url(r'^position/$', habits_views.locate_position, name='locate_position'),



    url(r'^habit/(?P<pk>\d+)$', habits_views.HabitDetailView.as_view(), name='display_habit_details'),
    url(r'^habit/(?P<pk>\d+)/update$', habits_views.HabitUpdateView.as_view(), name='update_habit'),
    url(r'^habit/update/complete$', habits_views.update_habit_complete, name='update_habit_complete'),
    url(r'^habit/(?P<pk>\d+)/delete$', habits_views.HabitDeleteView.as_view(), name='delete_habit'),
    url(r'^habit/(?P<id>\d+)/share/tweet', habits_views.tweet_habit, name='tweet_habit'),
    url(r'^habit/(?P<id>\d+)/share/post', habits_views.post_habit, name='post_habit'),
    url(r'^habit/(?P<id>\d+)/share/gplus', habits_views.gplus_habit, name='gplus_habit'),
    url(r'^habit/(?P<id>\d+)/share/mail', habits_views.mail_habit, name='mail_habit'),

    #url(r'^habit/details/(?P<id>\w{0,50})/$', habits_views.display_habit_details, name='display_habit_details'),
    #url(r'^habit/details/(?P<id>\w{0,50})/delete/$', habits_views.delete_habit, name='delete_habit'),
    #url(r'^habit/details/(?P<id>\w{0,50})/update/$', habits_views.update_habit, name='update_habit'),
    #url(r'^habit/details/(?P<pk>\w{0,50})/upate/$', habits_views.HabitUpdate.as_view(), name='update_habit'),

    # State
    url(r'^habit/state/$', habits_views.set_state, name='set_state'),

    # Comments
    url(r'^habit/comment/save/$', habits_views.save_comment, name='save_comment'),
    url(r'^habit/comments/$', habits_views.get_comments, name='get_comments'),


    url(r'^habit/create/$', habits_views.display_habitToCreate, name='display_habitToCreate'),
    url(r'^habit/save/$', habits_views.save_habit, name='save_habit'),
    # url(r'^habit/markdown_uploader/$', habits_views.markdown_uploader, name='markdown_uploader_page'),
    url(r'^habit/upload_habit_image/$', habits_views.upload_habit_image, name='upload_habit_image'),
    # url(r'^habit/edit/$', habits_views.edit_habit,     name='edit_habit'),




    url(r'^existingroutines/$', habits_views.display_existing_routines, name='display_existing_routines'),
    url(r'^existingroutines/create/$', habits_views.create_existing_routine, name='create_existing_routine'),
    url(r'^existingroutines/select/(?P<id>\w{0,50})/$', habits_views.select_existing_routine, name='select_existing_routine'),
    url(r'^existingroutines/update/(?P<pk>\w{0,50})/$', habits_views.ExistingroutineUpdate.as_view(), name='update_existing_routine'),
    url(r'^existingroutines/delete/(?P<pk>\w{0,50})/$', habits_views.ExistingroutineDelete.as_view(), name='delete_existing_routine'),
    url(r'^targetbehavior/$', habits_views.display_targetbehavior, name='display_targetbehavior'),
    url(r'^targetbehavior/create/$', habits_views.create_targetbehavior, name='create_targetbehavior'),
    url(r'^targetbehavior/select/(?P<id>\w{0,50})/$', habits_views.select_targetbehavior, name='select_targetbehavior'),
    url(r'^targetbehavior/update/(?P<pk>\w{0,50})/$', habits_views.TargetbehaviorUpdate.as_view(), name='update_targetbehavior'),
    url(r'^targetbehavior/delete/(?P<pk>\w{0,50})/$', habits_views.TargetbehaviorDelete.as_view(), name='delete_targetbehavior'),
]

habitusProject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.shortcuts import render, redirect

urlpatterns = [
    url(r'^$', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls')),
    url(r'^overview/', include('habits.urls')),
    #url(r'^overview/', include('overview.urls')),
    #url(r'^home/', include('login.urls')),
    #url(r'^registration/$', include('registration.urls')),
    #url(r'^password_reset/$', include('login.urls')),
    #url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    #url(r'^login/$', include('login.urls')),
    #url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
    #url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', register_views.activate, name='activate'),
    #url(r'^account_activation_sent/$', register_views.account_activation_sent, name='account_activation_sent'),
    #url(r'^registration/', include('registration.urls')),
    #url(r'^login/', include('login.urls')),
    #url(r'^$', core_views.home, name='home'),
    #url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    #url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    #url(r'^signup/$', core_views.signup, name='signup'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)

    def __str__(self):
        return self.user.username

    def image_url(self):
        #print(self.image.url)
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return '/media/profile_image/dummy_avatar.jpg'


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from accounts.models import UserProfile


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class EditProfileForm(UserChangeForm):
    image = forms.ImageField(required=False)
    class Meta:
        model = User
        fields = {
            'first_name', 'last_name', 'email', 'password', 'image'
        }

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = [
            'image',
        ]
def save(self, commit=True):
  user = super(UserProfileForm, self).save(commit=False)
  user.image = self.cleaned_data['image']

  if commit:
      user.save()

  return user

accounts/templates/accounts/display_account_disable_confirm.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style_profile.css' %}" />
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}" /> -->
{% endblock %}

{% block body %}
<div class="row" style="margin-top: 60px;margin-right:auto;margin-left:auto;">
  <p style="text-align:center; font-weight:bold;">
    <!--   Are you sure you want to deactivate your account? You won't log in to your
      user account anymore. For Reactivation please refer to the admin. -->
    Sind sie sicher, dass sie ihren Account deaktivieren möchten? Danach werden
    sie sich nicht mehr in ihren Account einloggen können. Für eine Reaktivierung
    wenden sie sich bitte an den Administrator.
  </p>
</div>
<br>
<form action="{% url 'disable_account_confirm' %}" method="post">
  {% csrf_token %}
  <div class="row" style="width:100%;" >
    <div class="col-xs-1"></div>
    <div class="col-xs-6"><input class="btn btn-danger" type="submit" value="Ja, ich bin mir sicher." /></div>
    <div class="col-xs-4"><a  href="{% url 'view_profile' %}" class="btn btn-default">Zurück</a></div>

  </div>
</form>

{% endblock %}

accounts/templates/accounts/display_password_reset.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style_reset_password.css' %}" />
{% endblock %}

{% block title %}Password reset{% endblock %}

{% block body %}
<div class="row" style="margin-top: 60px;margin-right:auto;margin-left:auto;width:100%;">
  <p style="text-align:center; font-weight:bold;">
    <!-- Forgotten your password? Enter your email address below, and
    we'll email instructions for setting a new one. -->
    Haben sie ihr Passwort vergessen? Geben sie unten einfach ihre E-Mail-Adresse ein und wir senden
    ihnen umgehend eine Nachricht, in der sie weitere Instruktionen erhalten, um ein neues Passwort
    setzen zu können.
  </p>
</div>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
  <div class="row" style="margin-top: 10px;width:100%;">
    <div class="col-xs-10 col-xs-offset-1">
      <input type="email" name="email" id="id_email" placeholder="E-Mail" required></input>
    </div>
  </div>
  <br>
  {% endfor %}
  <div class="row" style="text-align: center; width:100%; ">
    <div class="col-xs-10 col-xs-offset-1">
      <button id="id_btn_pw_reset" class="btn btn-primary" type="submit">Passwort zurücksetzen</button>
    </div>
  </div>
</form>

{% endblock %}

accounts/templates/accounts/display_password_reset_complete.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style_reset_password.css' %}" />
{% endblock %}

{% block title %}Password reset complete{% endblock %}

{% block body %}
<div class="row" style="margin-top: 60px;margin-right:auto;margin-left:auto;">
  <p style="text-align:center; font-weight:bold;">
    Ihr Passwort wurde erfolgreich geändert. Möglicherweise möchten sie
    fortfahren und sich
    <!-- Your password has been set. You may go ahead and. -->
  </p>
  <p style="text-align:center; font-weight:bold;">
  <a href="{% url 'login' %}">einloggen</a>.
  </p>
</div>
{% endblock %}

accounts/templates/accounts/display_password_reset_confirm.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style_reset_password.css' %}" />
{% endblock %}

{% block title %}Password reset{% endblock %}

{% block body %}
<div class="row" style="margin-top: 60px;margin-right:auto;margin-left:auto; width:100%">
  <p style="text-align:center;font-weight:bold;">
    Bitten geben sie nun ihr neues Passwort zweimal ein, sodass wir verizifzieren,
    dass sie dieses korrekt eingegeben haben.
    <!-- Please enter your new password twice so we can verify you typed it in correctly. -->
  </p>
</div>
<br>
<form method="POST">
  {% csrf_token %}
  <div class="row" style="text-align: center; width:100%;">
    <div class="col-xs-10 col-xs-offset-1">
      <input type="password" name="new_password1" required id="id_new_password1" placeholder="Neues Passwort"></input>
    </div>
  </div>
  <br>
  <div class="row" style="text-align: center; width:100%;">
    <div class="col-xs-10 col-xs-offset-1">
      <input type="password" name="new_password2" required id="id_new_password2" placeholder="Neues Passwort bestätigen"></input>
    </div>
  </div>
  <br>
  <div class="row" style="text-align: center;width:100%;">
    <div class="col-xs-10 col-xs-offset-1">
        <button id="id_btn_pw_reset_confirm" class="btn btn-primary" type="submit">Passwort ändern</button>
    </div>
  </div>


</form>

{% endblock %}

accounts/templates/accounts/display_password_reset_done.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style_reset_password.css' %}" />
{% endblock %}

{% block title %}Password reset{% endblock %}

{% block body %}
<div class="row" style="margin-top: 60px;margin-right:auto;margin-left:auto;">
  <p style="text-align:center; font-weight:bold;">
    Wir haben ihnen eine E-Mail mit weiteren Instruktionen, wie sie ein neues
    Passwort setzen können, zugesendet. Sie sollten diese in Kürze erhalten.
    Falls sie keine E-Mail zugesendet bekommen haben, ist möglicherweise die
    von ihnen eingegebene E-Mail-Adresse falsch oder die E-Mail liegt im Spam
    Ordner.

    Beachten sie die E-Mail-Adresse anzugeben, mit der sie sich auch registriert
    haben!
    <!-- We've emailed you instructions for setting your password, if an account
    exists with the email you entered. You should receive them shortly.
    If you don't receive an email, please make sure you've entered the
    address you registered with, and check your spam folder. -->
  </p>
</div>
{% endblock %}

accounts/templates/accounts/display_profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% load staticfiles %}
{% block head %}
  <!-- <link rel="stylesheet" href="{% static 'habits/css/style.css' %}" type="text/css"> -->
  <link rel="stylesheet" href="{% static 'accounts/css/style_profile.css' %}" type="text/css">
{% endblock %}

{% block body %}
<div class="row" style="margin-top:50px; margin-left:auto; margin-right:auto; width:100%;">
  <div class="col-xs-8">
    <div class="row" style="width:100%;">
      <br>
      <div class="col-xs-6">
        <p>Benutzername:</p>
      </div>
      <div class="col-xs-6">
        <p>{{user}}</p>
      </div>
    </div>
    <div class="row" style="width:100%;">
      <div class="col-xs-6">
        <p>Vorname:</p>
      </div>
      <div class="col-xs-6">
        <p>{{user.first_name}}</p>
      </div>
    </div>
    <div class="row" style="width:100%;">
      <div class="col-xs-6">
        <p>Nachname:</p>
      </div>
      <div class="col-xs-6">
        <p>{{user.last_name}}</p>
      </div>
    </div>
    <div class="row" style="width:100%;">
      <div class="col-xs-6">
        <p>E-Mail:</p>
      </div>
      <div class="col-xs-6">
        <p>{{user.email}}</p>
      </div>
    </div>
    <div class="row" style="width:100%;">
      <div class="col-xs-6">
        <p>Telefon:</p>
      </div>
      <div class="col-xs-6">
        <p>{{user.userprofile.phone}}</p>
      </div>
    </div>
    <div class="row" style="width:100%;">
      <div class="col-xs-6">
        <p>Stadt:</p>
      </div>
      <div class="col-xs-6">
        <p>{{user.userprofile.city}}</p>
      </div>
    </div>
    <div class="row" style="width:100%;">
      <div class="col-xs-6">
        <p>Webseite:</p>
      </div>
      <div class="col-xs-6">
        <p>{{user.userprofile.website}}</p>
      </div>
    </div>
  </div>
  <div class="col-xs-4">
    <img id="profile-image" src="{{ user.userprofile.image_url }}" class="img-responsive">
  </div>
</div>
<br>
<br>
<br>
<div class="row" style="text-align: center; width:100%;">
  <div class="col-xs-10 col-xs-offset-1">
    <a id="id_btn_disable_account" class="btn btn-primary" href="{% url 'disable_account_confirm' %}">Account deaktivieren<a/>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/display_profile_update.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block head %}
  <!-- <link rel="stylesheet" href="{% static 'habits/css/style.css' %}" type="text/css"> -->
  <link rel="stylesheet" href="{% static 'accounts/css/style_profile.css' %}" type="text/css">
{% endblock %}

{% block title %}Edit profile{% endblock %}

{% block body %}
<form action="{% url 'edit_profile' %}"  method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row" style="margin-top:50px; margin-left:auto; margin-right:auto; width:100%">
    <div class="col-xs-8">
      <div class="row" style="width:100%;">
        <br>
        <div class="col-xs-6">
          <p>Benutzername:</p>
        </div>
        <div class="col-xs-6">
          <p>{{user.userprofile.user}}</p>
        </div>
      </div>
      <div class="row" style="width:100%;">
        <div class="col-xs-6">
          <p>Vorname:</p>
        </div>
        <div class="col-xs-6">
          <p><input type="text" id="id_first_name" name="first_name" value="{{user.first_name}}"/></p>
        </div>
      </div>
      <div class="row" style="width:100%;">
        <div class="col-xs-6">
          <p>Nachname:</p>
        </div>
        <div class="col-xs-6">
          <p><input type="text" id="id_last_name" name="last_name" value="{{user.last_name}}"/></p>
        </div>
      </div>
      <div class="row" style="width:100%;">
        <div class="col-xs-6">
          <p>E-Mail:</p>
        </div>
        <div class="col-xs-6">
          <p><input type="text" id="id_email" name="email" value="{{user.email}}"/></p>
        </div>
      </div>
      <div class="row" style="width:100%;">
        <div class="col-xs-6">
          <p>Telefon:</p>
        </div>
        <div class="col-xs-6">
          <p><input type="text" id="id_phone" name="phone" value="{{user.userprofile.phone}}"></input></p>
        </div>
      </div>
      <div class="row" style="width:100%;">
        <div class="col-xs-6">
          <p>Stadt:</p>
        </div>
        <div class="col-xs-6">
          <p><input type="text" id="id_city" name="city" value="{{user.userprofile.city}}"></input></p>
        </div>
      </div>
      <div class="row" style="width:100%;">
        <div class="col-xs-6">
          <p>Webseite:</p>
        </div>
        <div class="col-xs-6">
          <p><input type="text" id="id_website" name="website" value="{{user.userprofile.website}}"></input></p>
        </div>
      </div>
    </div>
    <div class="col-xs-4">
      <img id="profile_image" src="{{ user.userprofile.image_url }}" class="img-responsive">
      <input type="file" id="id_image" name="image" onchange="readURL(this);" style="display:none;" />
      <!--  style="display:none;"  -->
    </div>
  </div>

  <br>
  <br>
  <br>
  <div class="row" style="text-align: center; width:100%;">
    <div class="col-xs-10 col-xs-offset-1">
      <button  id="id_btn_change_profile" type="submit" class="btn btn-primary">Änderungen übernehmen</button>
    </div>
  </div>
</form>


{% endblock %}

{% block script %}
<script src="{% static 'accounts/js/edit-profile.js' %}"></script>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block head %}
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}" /> -->
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style_login.css' %}" />
  <!-- <link rel="stylesheet" type="text/css"  href="{% static 'css/bootstrap/bootstrap.css' %}" /> -->
{% endblock %}

{% block title %}Login{% endblock %}

{% block body %}

  <div class="row" style="margin-top: 30px; width:100%">
    <h4 style="text-align:center; font-weight: bold;margin-top: 30px">Melde Dich bei DO IT! an</h4>
  </div>
  <br>
  <form method="post">
    {% csrf_token %}
    <div class="row" style="text-align: center;width:100%;">
      <div class="col-xs-10 col-xs-offset-1">
        <input type="text" name="username" id="id_username" required placeholder="E-Mail oder Nutzername" class=".btn-round-lg"></input>
      </div>
    </div>
    <br>
    <div class="row" style="text-align: center; width:100%;">
      <div class="col-xs-10 col-xs-offset-1">
        <input type="password" name="password" required id="id_password" placeholder="Passwort"></input>
      </div>
    </div>
    <br>
    <div class="row" style="text-align: center; width:100%;">
      <div class="col-xs-10 col-xs-offset-1">
        <button id="id_btn_login" class="btn btn-primary" type="submit">Anmelden</button>
      </div>
    </div>
  </form>
  <div class="row" style="text-align: center; width:100%;">
    <div class="col-xs-8 col-xs-offset-2">
      <a class="login-alternatives" href="reset_password">Passwort vergessen?</a> ·
      <a class="login-alternatives" href="{% url 'registration' %}">Bei DO IT! registrieren</a>
    </div>
  </div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block head %}
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}" /> -->
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style_login.css' %}" />
{% endblock %}

{% block title %}See you!{% endblock %}

{% block body %}
  <div class="container">
    <br>
    <br>
    <br>
    <!-- <h2 style="text-align:center;">Logged out</h2>
    <hr> -->
    <p style="text-align:center; font-weight:bold;">Sie haben sich erfolgreich abgemeldet.</p>
    <!-- <p style="text-align:center;"><a href="{% url 'login' %}">Log in</a> again.</p> -->
  </div>
{% endblock %}

accounts/templates/accounts/registration.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style_login.css' %}" />
{% endblock %}

{% block title %}Register{% endblock %}

{% block body %}
  <div class="container" style="margin-top: 40px;">
    <div class="row">
      <h4 style="text-align:center; font-weight: bold;">Willkommen bei DO IT!</h4>
    </div>
    <br>
    <form method="post">
      {% csrf_token %}
      <div class="row" style="margin-top: 10px;">
        <div class="col-xs-10 col-xs-offset-1">
          <input type="text" name="username" id="id_username" placeholder="Nutzername" required></input>
        </div>
      </div>
      <div class="row" style="margin-top: 10px;">
        <div class="col-xs-10 col-xs-offset-1">
          <input type="text" name="firstname" id="id_firstname" placeholder="Vorname"></input>
        </div>
      </div>
      <div class="row" style="margin-top: 10px;">
        <div class="col-xs-10 col-xs-offset-1">
          <input type="text" name="lastname" id="id_lastname" placeholder="Nachname"></input>
        </div>
      </div>
      <div class="row" style="margin-top: 10px;">
        <div class="col-xs-10 col-xs-offset-1">
          <input type="email" name="email" id="id_email" placeholder="E-Mail" required></input>
        </div>
      </div>
      <div class="row" style="margin-top: 10px;">
        <div class="col-xs-10 col-xs-offset-1">
          <input type="password" name="password1" id="id_password1" placeholder="Passwort"></input>
        </div>
      </div>
      <div class="row" style="margin-top: 10px;">
        <div class="col-xs-10 col-xs-offset-1">
          <input type="password" name="password2" id="id_password2" placeholder="Passwort bestätigen"></input>
        </div>
      </div>
      <div class="row" style="margin-top: 20px; text-align: center;">
        <div class="col-xs-10 col-xs-offset-1">
          <button id="id_btn_register" type="submit" class="btn btn-primary">Registrieren</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/login_style.css' %}" />
{% endblock %}

{% block title %}Password reset{% endblock %}

{% block body %}
<div class="row" style="margin-top: 60px;margin-right:auto;margin-left:auto;">
  <p style="text-align:center; font-weight:bold;">
    <!-- Forgotten your password? Enter your email address below, and
    we'll email instructions for setting a new one. -->
    Haben sie ihr Passwort vergessen? Geben sie unten einfach ihre E-Mail-Adresse ein und wir senden
    ihnen umgehend eine Nachricht, in der sie weitere Instruktionen erhalten, um ein neues Passwort
    setzen zu können.
  </p>
</div>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
  <div class="row" style="margin-top: 10px;">
    <div class="col-xs-10 col-xs-offset-1">
      <input type="email" name="email" id="id_email" placeholder="E-Mail" required></input>
    </div>
  </div>
  <br>
  {% endfor %}
  <div class="row" style="text-align: center;">
    <div class="col-xs-10 col-xs-offset-1">
      <button id="id_btn_pw_reset" class="btn btn-primary" type="submit">Passwort zurücksetzen</button>
    </div>
  </div>
</form>

{% endblock %}